apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "name" . }}
spec:
  host: {{ template "name" . }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: {{ .Values.subset.version }}
    labels:
      version: {{ .Values.subset.version }}
