apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ibmgarageforcloud-com
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.ibmgarageforcloud.com"
    #      tls:
    #        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*.ibmgarageforcloud.com"
      tls:
        mode: SIMPLE
        credentialName: wildcard-ibmgarageforcloud-com
