apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
    - "{{ .Values.service.name }}.ibmgarageforcloud.com"
  gateways:
    - {{ .Values.service.name }}
  http:
    - route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: 3001
