apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
    - "{{ .Values.ingress.itemsPath }}"
  gateways:
    - "{{ .Values.ingress.gateway }}"
  http:
    - route:
        - destination:
#            subset: {{ .Values.subset.version }}
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.appPort }}
