{{ if .Values.gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
    - "{{ .Values.gateway.host }}"
  gateways:
    - "{{ .Values.gateway.name }}"
  http:
    - route:
        - destination:
            # subset: {{ .Values.subset.version }}
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.servicePort }}
{{ end }}