replicaCount: 2
revisionHistoryLimit: 3
subset:
  version: v1
image:
  repository: michaelsteven
  name: react-items-ui
  tag: latest
  pullPolicy: Always
  runAsUser: 1001
service:
  name: react-items-ui
  type: ClusterIP
  appPort: 3001
resources: {}
ingress:
  gateway: ibmgarageforcloud-com
  appName: react-items-ui
  tlsSecretName: wildcard-ibmgarageforcloud-com
  itemsPath: react-items-ui.ibmgarageforcloud.com
